#!/bin/sh

set -ex

# The script will assume you that you\'re on the edge repository and not on stable (in Debian terms, it's
# latest stable version/release) There are some stuff that I didn't include here assuming that your Linux
# setup would be separate home directory for ease installation process.

SCREEN_NAME="Stick Michael"
USERNAME="gildedguy"

# Basics: you should use doas instead in daily admin ops
apk add bash zsh git git-lfs github-cli coreutils procps mandoc mandoc-apropos doas
# Documentation stuff goes here, because I don't have time
apk add bash-doc coreutils-doc git-doc git-lfs-doc man-pages mandoc-doc zsh-doc
# shell completions
apk add git-bash-completion github-cli-bash-completion github-cli-zsh-completion
# development packages
apk add python3 python3-doc python3-dev nodejs nodejs-doc py3-pip-bash-completion py3-pip py3-pip-zsh-completion py3-pip-doc

# setup user and some doas prep
#adduser -g "$SCREEN_NAME" $USERNAME
#adduser $USERNAME video
#adduser $USERNAME audio
#adduser $USERNAME wheel
echo "permit persist :wheel" >> /etc/doas.conf

# setup xorg server first
setup-xorg-server
# xfce basics + KDE Breeze theme stuff
apk add xfce4 xfce4-terminal xfce4-screensaver lightdm-gtk-greeter breeze breeze-gtk adwaita-gtk2-theme adwaita-icon-theme elogind polkit-elogind
# automounting kek and bloody pulseaudio BS
apk add gvfs udisks2 ntfs-3g pulseaudio pulseaudio-alsa alsa-plugins-pulse
# TODO: Firefox anyone?
