#!/bin/bash

# these commands should be triggered on shell startup
source "$DOTFILES_HOME/config/bashrc/aliases"
source "$DOTFILES_HOME/config/bashrc/functions"

if ! command -v keychain >> /dev/null; then
  keychain ~/.ssh/personal ~/.ssh/ajhalili2006.recaptime.dev
fi
