#!/bin/env bash

# Start GPG and SSH agents
export GPG_TTY=$(tty)
# Use OkcAgent's SSH agent client to use my GPG key for SSH sessions.
if ! pgrep okc-ssh-agent > /dev/null; then
    okc-ssh-agent > "$PREFIX/tmp/okc-ssh-agent.env"
fi
source "$PREFIX/tmp/okc-ssh-agent.env"

if ! pgrep sshd > /dev/null; then
    sshd
fi

# Then add my scripts
export DOTFILES_STUFF_BIN="$HOME/.dotfiles/bin"
export PATH=$PATH:$DOTFILES_STUFF_BIN:$HOME/.local/bin
export DOTFILES_HOME=$HOME/.dotfiles
# clean up bash history
#echo
#rm -rf ~/.bash_history>>/dev/null && history -c && echo "history-cleanup: Shell history cleaned for past session" || echo "history-cleanup: No bash_history file found for past session."

# then do chain sourcing
source ~/.dotfiles/config/bashrc/chain-source

